### ISSUE TITLE
how to capture passport of patient

### ISSUE THREAD

**Issue by noxecane** [tsaron/dariya#2]
The current [patient registeration form](https://beta.hospitalrun.io/#/patients/edit/new) does not give a user the ability to add a patient's passport to his records. There should be a field for taking pictures(using webcam) of patient's during registeration

**Comment by waleplanet** [comment]
![screenshot from 2017-05-03 16-48-01](https://cloud.githubusercontent.com/assets/9745471/25669831/b40deca2-3022-11e7-8237-c6bdeeef509f.png)

**Comment by waleplanet** [comment]
capturing passport with webcam

**Comment by danceasarxx** [comment]
please don't close issues, that's up to me
